### ISSUE TITLE
document build auth tables

### ISSUE THREAD

**Issue by webineh** [simple-mvc-framework/docs#18]
how i can run script folder ! i don't see document about build table auth system

**Comment by ghost** [comment]
Import the `*.sql` scripts via your CPanel or mysql program (i.e. HeidiSQL)

For auth, you would want:

- nova_roles.sql
- nova_users.sql
- nova_password_reminders.sql

If you are on version 4 or above (full, not bare), then use `php forge module:migrate users`

**Comment by LuckyCyborg** [comment]
@vahidalvandi 

> how i can run script folder ! i don't see document about build table auth system

This repository is NOT for support and I see that you have NO ISSUE to report about docs.

Please stop asking for help on whatever repository you like!

For help and support we have https://gitter.im/nova-framework/framework/novausers
