### ISSUE TITLE
[4.0] To Do List

### ISSUE THREAD

**Issue by ghost** [simple-mvc-framework/docs#28]
I know it technically isn't an issue, but I keep forgetting what needs to be done for the documentation. So decided to do a task list. If anyone wants to do documentation for any of the below, feel free to and reference this issue.

## To Do

- [ ] Cache
- [X] Template (PR: **[Update Templates.md](https://github.com/nova-framework/docs/pull/30)** Commit: 	19c3f66)
- [ ] Queue
- [ ] Modules
- [ ] Widgets
- [X] whereMonth and whereDay for ORM (PR: **[Date Filtering for ORM](https://github.com/nova-framework/docs/pull/29)** Commit: fa48c79)

If I am missing any, comment below.

**Comment by LuckyCyborg** [comment]
@Kingorgg What happened? Why you closed this issue?
