### ISSUE TITLE
issue installing nova on ubuntu14.04

### ISSUE THREAD

**Issue by Thejaswini21** [simple-mvc-framework/docs#32]
As i mentioned , i just wanted to knw the installation steps for nova on ubuntu14.04,

i can learn using documentation , that i have done.
installation in xampp and ubuntu14.04 is different..i hope this you know.

Your both link is not opening

Thanks & regards
Thejas

**Comment by Thejaswini21** [comment]
And i have not used any example programs to site..
first of all im not able to register in admin part after installtion as xampp steps mentioned in document..
In document xamp , iis nginx installation steps has given , but not ubuntu14.04..

**Comment by dcblogdev** [comment]
hi there was an change added to the register controller earlier that may solve your issue I'm not a ubuntu user but I've just installed a vm and then installed composer:

```
sudo apt install composer
```

next installed php 7:

```
sudo apt-get install php7.0-intl
```

then installed nova:

```
composer create-project nova-framework/framework nova 3.* -s dev
```

then moved into nova folder and ran:

```
php forge serve
```

which booted the framework and ran that in firefox.
