### ISSUE TITLE
php forge seed seems to be deprecated

### ISSUE THREAD

**Issue by yogimishra96** [simple-mvc-framework/docs#36]
installation guide says  
https://novaframework.com/documentation/v3/install#recommended

![screenshot from 2018-04-11 17-07-25](https://user-images.githubusercontent.com/12248100/38614542-2681cf42-3dab-11e8-87a0-6ee746cd5eb3.png)

but in 

> php forge seed

 it shows

![nova](https://user-images.githubusercontent.com/12248100/38614490-ff9d3d6c-3daa-11e8-91ab-1e5a97f14e21.png)

**Comment by dcblogdev** [comment]
thanks I'll update this.
